spring:
  application:
    name: insurance
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/insurance?authSource=admin
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
    topic:
      payment-notification:
        queue: payment-notification-update
      subscription-notification:
        queue: subscription-notification-update
      status-update:
        exchange: insurance-topic-exchange
        queue: insurance.queue
        routing-key: insurance.status-update
  client:
    fraud-rest-service:
      url: localhost:8081/fraud
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
info:
  app:
    name: insurance-service
    description: API de gerenciamento de seguros
    version: 1.0.0

feign:
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 5000
        loggerLevel: full